#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "Utility/CapsuleComponentUtilities.h"
#include "CapsuleSpawnerComponent.generated.h"

class UCapsuleComponent;

/**
 * A component that spawns points within a Capsule defined by a UCapsuleComponent. It allows for customizable spawn parameters, randomization, and debug visualization of the spawn area and last spawn point.
 */
UCLASS( ClassGroup=(Custom), meta=(BlueprintSpawnableComponent) )
class PERICULUM_API UCapsuleSpawnerComponent : public UActorComponent
{
	GENERATED_BODY()

public:	
	UCapsuleSpawnerComponent();

protected:
	virtual void BeginPlay() override;
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
	virtual void OnRegister() override;

public:	
	/// <summary>
	/// The CapsuleComponent that defines the spawn area. This component should be a UCapsuleComponent and will be used to determine the bounds for spawning points.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule Spawning")
	TObjectPtr<UCapsuleComponent> CapsuleComponent;
	
	/// <summary>
	/// The parameters that define how points are spawned within the capsule. This includes settings such as spawn density, randomization, and other relevant parameters.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule Spawning")
	FCapsuleSpawnParams SpawnParams;

	/// <summary>
	/// The history of spawn data generated by this component. This array stores the most recent spawn points, up to a maximum defined by MaxSpawnHistory.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule Spawning")
	TArray<FCapsuleSpawnData> SpawnHistory;

	/// <summary>
	/// The maximum number of spawn points to keep in the SpawnHistory array. When the number of generated spawn points exceeds this value, the oldest entries will be removed to maintain the limit.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule Spawning")
	int32 MaxSpawnHistory = 100;
	
	/// <summary>
	/// The seed value used for random number generation when spawning points. This allows for reproducible randomization of spawn points within the capsule. If set to 0, a random seed will be generated.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule Spawning")
	int32 RandomSeed = 0;

	/// <summary>
	/// The random stream used for generating random numbers when spawning points. This stream is initialized with the RandomSeed and is used to ensure consistent randomization across multiple spawn operations.
	/// </summary>
	UPROPERTY()
	FRandomStream RandomStream;

	/// <summary>
	/// Whether to draw debug visualization of the spawn area defined by the CapsuleComponent. When enabled, the capsule will be drawn in the editor and during gameplay to help visualize the spawn area.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule Spawning")
	bool bDebugDrawArea = true;

	/// <summary>
	/// Whether to draw debug visualization of the last spawn point generated by this component. When enabled, the last spawn point will be drawn in the editor and during gameplay to help visualize where the most recent point was spawned.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule Spawning")
	bool bDebugDrawLastPoint = true;

public:
	/// <summary>
	/// Sets the spawn parameters for this component. This function allows you to update the spawn parameters at runtime, enabling dynamic changes to how points are spawned within the capsule.
	/// </summary>
	/// <param name="InParams">The new spawn parameters to set.</param>
	UFUNCTION(BlueprintCallable, Category = "Capsule Spawning")
	void SetSpawnParams(const FCapsuleSpawnParams& InParams) { SpawnParams = InParams; }

	/// <summary>
	/// Clears the spawn history, removing all previously generated spawn points from the SpawnHistory array. This can be useful for resetting the state of the component or starting a new spawning session.
	/// </summary>
	UFUNCTION(BlueprintCallable, Category = "Capsule Spawning")
	void ClearSpawnHistory() { SpawnHistory.Empty(); }

	/// <summary>
	/// Sets the random seed for the random stream used in spawning points. This allows for reproducible randomization of spawn points within the capsule. If you want to generate a new random seed, you can call this function with a new value.
	/// </summary>
	/// <param name="InSeed">The new random seed to set.</param>
	UFUNCTION(BlueprintCallable, Category = "Capsule Spawning")
	void SetRandomSeed(int32 InSeed) { RandomSeed = InSeed; RandomStream.Initialize(RandomSeed); }

	/// <summary>
	/// Draws debug visualization of the spawn area defined by the CapsuleComponent. This function can be called to visualize the capsule in the editor and during gameplay, helping to understand the bounds within which points will be spawned.
	/// </summary>
	UFUNCTION(BlueprintCallable, Category = "Capsule Spawning")
	void DrawDebugSpawnArea() const;

	/// <summary>
	/// Draws debug visualization of the last spawn point generated by this component. This function can be called to visualize the most recent spawn point in the editor and during gameplay, helping to understand where the last point was spawned within the capsule.
	/// </summary>
	UFUNCTION(BlueprintCallable, Category = "Capsule Spawning")
	void DrawDebugLastSpawnPoint() const;

	/// <summary>
	/// Generates a new spawn point within the capsule defined by the CapsuleComponent, based on the current SpawnParams and RandomStream. This function returns the generated spawn data without storing it in the SpawnHistory array.
	/// </summary>
	/// <returns>The generated spawn data.</returns>
	UFUNCTION(BlueprintCallable, Category = "Capsule Spawning")
	FCapsuleSpawnData GenerateSpawnData();

	/// <summary>
	/// Generates a new spawn point within the capsule defined by the CapsuleComponent, based on the current SpawnParams and RandomStream. This function stores the generated spawn data in the SpawnHistory array, maintaining the maximum history size defined by MaxSpawnHistory.
	/// </summary>
	/// <returns>The generated spawn data.</returns>
	UFUNCTION(BlueprintCallable, Category = "Capsule Spawning")
	FCapsuleSpawnData GenerateAndStoreSpawnData();

private:
	/// <summary>
	/// The last spawn location generated by this component. This variable is used for debug visualization and can be accessed to determine where the most recent point was spawned within the capsule.
	/// </summary>
	FVector LastSpawnLocation;
};
