#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "Utility/SphereComponentUtilities.h"

#include "SphereSpawnerComponent.generated.h"

class USphereComponent;

/**
 * A component that spawns points within a sphere defined by a USphereComponent. It allows for customizable spawn parameters, randomization, and debug visualization of the spawn area and last spawn point.
 */
UCLASS( ClassGroup=(Custom), meta=(BlueprintSpawnableComponent) )
class PERICULUM_API USphereSpawnerComponent : public UActorComponent
{
	GENERATED_BODY()

public:	
	USphereSpawnerComponent();

protected:
	virtual void BeginPlay() override;
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
	virtual void OnRegister() override;
public:	
	/// <summary>
	/// A pointer to a USphereComponent used for sphere spawning.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere Spawning")
	TObjectPtr<USphereComponent> SphereComponent;

	/// <summary>
	/// The parameters used for spawning within the sphere.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere Spawning")
	FSphereSpawnParams SpawnParams;

	/// <summary>
	/// History of spawn data generated by the component, stored as an array of FSphereSpawnData.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere Spawning")
	TArray<FSphereSpawnData> SpawnHistory;

	/// <summary>
	/// The maximum number of spawn history entries to keep. When the limit is reached, older entries will be removed.
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere Spawning")
	int32 MaxSpawnHistory = 100;

	/// <summary>
	/// An integer property that specifies the seed used for sphere spawning. It is editable anywhere and exposed to Blueprints for reading and writing, categorized under "Sphere Spawning".
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere Spawning")
	int32 RandomSeed = 0;

	/// <summary>
	/// The random stream used for generating random values during sphere spawning. It is initialized with the specified RandomSeed and is not exposed to Blueprints or editable in the editor.
	/// </summary>
	UPROPERTY()
	FRandomStream RandomStream;

	/// <summary>
	/// Whether to draw debug visualization of the sphere spawning area. If true, the area will be drawn for debugging purposes. It is editable anywhere and exposed to Blueprints for reading and writing, categorized under "Sphere Spawning".
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere Spawning")
	bool bDebugDrawArea = true;

	/// <summary>
	/// Whether to draw debug visualization of the last spawn point. If true, the last spawn point will be drawn for debugging purposes. It is editable anywhere and exposed to Blueprints for reading and writing, categorized under "Sphere Spawning".
	/// </summary>
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere Spawning")
	bool bDebugDrawLastPoint = true;

public:
	/// <summary>
	/// Sets the spawn parameters for the sphere spawner component. This function allows you to update the spawn parameters used for generating spawn points within the sphere.
	/// It takes a constant reference to an FSphereSpawnParams structure as input and assigns it to the SpawnParams property of the component.
	/// </summary>
	/// <param name="InParams">The new spawn parameters to set.</param>
	UFUNCTION(BlueprintCallable, Category = "Sphere Spawning")
	void SetSpawnParams(const FSphereSpawnParams& InParams) {  SpawnParams = InParams; }

	/// <summary>
	/// Clears the recorded spawn history by emptying the SpawnHistory container.
	/// </summary>
	UFUNCTION(BlueprintCallable, Category = "Sphere Spawning")
	void ClearSpawnHistory() { SpawnHistory.Empty(); }

	/// <summary>
	/// Sets the random seed for the sphere spawner component and initializes the RandomStream with the specified seed. This function allows you to control the randomness of the spawn points generated within the sphere.
	/// </summary>
	/// <param name="InSeed">The new random seed to set.</param>
	UFUNCTION(BlueprintCallable, Category = "Sphere Spawning")
	void SetRandomSeed(int32 InSeed) { RandomSeed = InSeed; RandomStream.Initialize(RandomSeed); }

	/// <summary>
	/// Draws debug visualization of the sphere spawning area. If bDebugDrawArea is true, this function will render the sphere defined by the SphereComponent for debugging purposes.
	/// </summary>
	UFUNCTION(BlueprintCallable, Category = "Sphere Spawning")
	void DrawDebugSpawnArea() const;

	/// <summary>
	/// Draws debug visualization of the last spawn point generated by the sphere spawner component. If bDebugDrawLastPoint is true, this function will render a visual representation of the last spawn location for debugging purposes.
	/// </summary>
	UFUNCTION(BlueprintCallable, Category = "Sphere Spawning")
	void DrawDebugLastSpawnPoint() const;

	/// <summary>
	/// Generates a new spawn data point within the sphere defined by the SphereComponent, based on the current SpawnParams and RandomStream. 
	/// This function returns an FSphereSpawnData structure containing the generated spawn location and any other relevant information.
	/// </summary>
	/// <returns>The FSphereSpawnData structure containing the generated spawn data.</returns>
	UFUNCTION(BlueprintCallable, Category = "Sphere Spawning")
	FSphereSpawnData GenerateSpawnData();
	
	/// <summary>
	/// Generates a new spawn data point within the sphere defined by the SphereComponent, based on the current SpawnParams and RandomStream, and stores it in the SpawnHistory array.
	/// </summary>
	/// <returns>The FSphereSpawnData structure containing the generated spawn data.</returns>
	UFUNCTION(BlueprintCallable, Category = "Sphere Spawning")
	FSphereSpawnData GenerateAndStoreSpawnData();

private:
	/// <summary>
	/// The last spawn location generated by the sphere spawner component. This property is used for debug visualization of the last spawn point and is not exposed to Blueprints or editable in the editor.
	/// </summary>
	FVector LastSpawnLocation;
};
