FBoxSpawnData Struct Reference
#include <BoxComponentUtilities.h>
Public Member Functions
FBoxSpawnData ()
FBoxSpawnData (const FTransform &InTransform, const FVector &InDirection)
FBoxSpawnData (const FVector &InLocation, const FRotator &InRotation, const FVector &InScale, const FVector &InDirection)
Public Attributes
FVector SpawnDirection
FTransform SpawnTransform
Constructor & Destructor Documentation
FBoxSpawnData() [1/3]
FBoxSpawnData::FBoxSpawnData () [inline]
        : SpawnTransform(FTransform::Identity)
        , SpawnDirection(FVector::ForwardVector)
 
    {
    }
References FBoxSpawnData().
Referenced by FBoxSpawnData().
FBoxSpawnData() [2/3]
FBoxSpawnData::FBoxSpawnData (const FTransform & InTransform, const FVector & InDirection) [inline]
        : SpawnTransform(InTransform)
        , SpawnDirection(InDirection)
 
    {
    }
References FBoxSpawnData().
Referenced by FBoxSpawnData().
FBoxSpawnData() [3/3]
FBoxSpawnData::FBoxSpawnData (const FVector & InLocation, const FRotator & InRotation, const FVector & InScale, const FVector & InDirection) [inline]
        : SpawnTransform(FTransform(InRotation, InLocation, InScale))
        , SpawnDirection(InDirection)
    {
    }
References FBoxSpawnData().
Referenced by FBoxSpawnData().
Member Data Documentation
SpawnDirection
FVector FBoxSpawnData::SpawnDirection
SpawnTransform
FTransform FBoxSpawnData::SpawnTransform
The documentation for this struct was generated from the following file:
Source/Periculum/Public/Utility/BoxComponentUtilities.h