FCapsuleSpawnData Struct Reference
#include <CapsuleComponentUtilities.h>
Public Member Functions
FCapsuleSpawnData ()
FCapsuleSpawnData (const FTransform &InTransform, const FVector &InDirection)
FCapsuleSpawnData (const FVector &InLocation, const FRotator &InRotation, const FVector &InScale, const FVector &InDirection)
Public Attributes
FVector SpawnDirection
FTransform SpawnTransform
Constructor & Destructor Documentation
FCapsuleSpawnData() [1/3]
FCapsuleSpawnData::FCapsuleSpawnData () [inline]
        : SpawnTransform(FTransform::Identity)
        , SpawnDirection(FVector::ForwardVector)
    {
    }
References FCapsuleSpawnData().
Referenced by FCapsuleSpawnData().
FCapsuleSpawnData() [2/3]
FCapsuleSpawnData::FCapsuleSpawnData (const FTransform & InTransform, const FVector & InDirection) [inline]
        : SpawnTransform(InTransform)
        , SpawnDirection(InDirection)
    {
    }
References FCapsuleSpawnData().
Referenced by FCapsuleSpawnData().
FCapsuleSpawnData() [3/3]
FCapsuleSpawnData::FCapsuleSpawnData (const FVector & InLocation, const FRotator & InRotation, const FVector & InScale, const FVector & InDirection) [inline]
        : SpawnTransform(FTransform(InRotation, InLocation, InScale))
        , SpawnDirection(InDirection)
    {
    }
References FCapsuleSpawnData().
Referenced by FCapsuleSpawnData().
Member Data Documentation
SpawnDirection
FVector FCapsuleSpawnData::SpawnDirection
SpawnTransform
FTransform FCapsuleSpawnData::SpawnTransform
The documentation for this struct was generated from the following file:
Source/Periculum/Public/Utility/CapsuleComponentUtilities.h