FSphereSpawnData Struct Reference
#include <SphereComponentUtilities.h>
Public Member Functions
FSphereSpawnData ()
FSphereSpawnData (const FTransform &InTransform, const FVector &InDirection)
FSphereSpawnData (const FVector &InLocation, const FRotator &InRotation, const FVector &InScale, const FVector &InDirection)
Public Attributes
FVector SpawnDirection
FTransform SpawnTransform
Constructor & Destructor Documentation
FSphereSpawnData() [1/3]
FSphereSpawnData::FSphereSpawnData () [inline]
        : SpawnTransform(FTransform::Identity)
        , SpawnDirection(FVector::ForwardVector)
 
    {
    }
References FSphereSpawnData().
Referenced by FSphereSpawnData().
FSphereSpawnData() [2/3]
FSphereSpawnData::FSphereSpawnData (const FTransform & InTransform, const FVector & InDirection) [inline]
        : SpawnTransform(InTransform)
        , SpawnDirection(InDirection)
 
    {
    }
References FSphereSpawnData().
Referenced by FSphereSpawnData().
FSphereSpawnData() [3/3]
FSphereSpawnData::FSphereSpawnData (const FVector & InLocation, const FRotator & InRotation, const FVector & InScale, const FVector & InDirection) [inline]
        : SpawnTransform(FTransform(InRotation, InLocation, InScale))
        , SpawnDirection(InDirection)
    {
    }
References FSphereSpawnData().
Referenced by FSphereSpawnData().
Member Data Documentation
SpawnDirection
FVector FSphereSpawnData::SpawnDirection
SpawnTransform
FTransform FSphereSpawnData::SpawnTransform
The documentation for this struct was generated from the following file:
Source/Periculum/Public/Utility/SphereComponentUtilities.h