// Copyright Epic Games, Inc. All Rights Reserved.

#include "Periculum.h"
#include "Modules/ModuleManager.h"

IMPLEMENT_PRIMARY_GAME_MODULE( FDefaultGameModuleImpl, Periculum, "Periculum" );
 
DEFINE_LOG_CATEGORY(GAME);
DEFINE_LOG_CATEGORY(GAMEPLAY);
DEFINE_LOG_CATEGORY(HUD);

DEFINE_LOG_CATEGORY(PLAYER);
DEFINE_LOG_CATEGORY(INPUT);

DEFINE_LOG_CATEGORY(NPC);
DEFINE_LOG_CATEGORY(ENEMY);

DEFINE_LOG_CATEGORY(SFX);
DEFINE_LOG_CATEGORY(AUDIO);

DEFINE_LOG_CATEGORY(ENVIRONMENT);
DEFINE_LOG_CATEGORY(ITEM);
DEFINE_LOG_CATEGORY(WEAPON);
